import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "QUIZZLY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        {/* Global Background */}
        <div className="relative min-h-screen overflow-hidden bg-gradient-to-br from-black via-[#0f0c29] to-black">
          
          {/* Glow blobs */}
          <div className="pointer-events-none absolute -top-40 -left-40 h-96 w-96 rounded-full bg-indigo-600/20 blur-3xl" />
          <div className="pointer-events-none absolute top-1/3 -right-40 h-96 w-96 rounded-full bg-purple-600/20 blur-3xl" />

          {/* App Content */}
          <AuthProvider>
            <div className="relative z-10">
              <Header />
              {children}
            </div>
          </AuthProvider>

        </div>
      </body>
    </html>
  );
}
